<?php
/**
 * V1alpha1VolumeSnapshotStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1alpha1VolumeSnapshotStatusTest Class Doc Comment
 *
 * @category    Class
 * @description VolumeSnapshotStatus is the status of a VolumeSnapshot
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1alpha1VolumeSnapshotStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1alpha1VolumeSnapshotStatus"
     */
    public function testV1alpha1VolumeSnapshotStatus()
    {
    }

    /**
     * Test attribute "creation_time"
     */
    public function testPropertyCreationTime()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "ready_to_use"
     */
    public function testPropertyReadyToUse()
    {
    }

    /**
     * Test attribute "volume_snapshot_name"
     */
    public function testPropertyVolumeSnapshotName()
    {
    }
}
