<?php
/**
 * V1DeveloperConfigurationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1DeveloperConfigurationTest Class Doc Comment
 *
 * @category    Class
 * @description DeveloperConfiguration holds developer options
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1DeveloperConfigurationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1DeveloperConfiguration"
     */
    public function testV1DeveloperConfiguration()
    {
    }

    /**
     * Test attribute "cpu_allocation_ratio"
     */
    public function testPropertyCpuAllocationRatio()
    {
    }

    /**
     * Test attribute "feature_gates"
     */
    public function testPropertyFeatureGates()
    {
    }

    /**
     * Test attribute "log_verbosity"
     */
    public function testPropertyLogVerbosity()
    {
    }

    /**
     * Test attribute "memory_overcommit"
     */
    public function testPropertyMemoryOvercommit()
    {
    }

    /**
     * Test attribute "node_selectors"
     */
    public function testPropertyNodeSelectors()
    {
    }

    /**
     * Test attribute "pvc_tolerate_less_space_up_to_percent"
     */
    public function testPropertyPvcTolerateLessSpaceUpToPercent()
    {
    }

    /**
     * Test attribute "use_emulation"
     */
    public function testPropertyUseEmulation()
    {
    }
}
