<?php
/**
 * V1KubeVirtSelfSignConfigurationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1KubeVirtSelfSignConfigurationTest Class Doc Comment
 *
 * @category    Class
 * @description V1KubeVirtSelfSignConfiguration
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1KubeVirtSelfSignConfigurationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1KubeVirtSelfSignConfiguration"
     */
    public function testV1KubeVirtSelfSignConfiguration()
    {
    }

    /**
     * Test attribute "ca_overlap_interval"
     */
    public function testPropertyCaOverlapInterval()
    {
    }

    /**
     * Test attribute "ca_rotate_interval"
     */
    public function testPropertyCaRotateInterval()
    {
    }

    /**
     * Test attribute "cert_rotate_interval"
     */
    public function testPropertyCertRotateInterval()
    {
    }
}
