<?php
/**
 * V1VirtualMachineStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1VirtualMachineStatusTest Class Doc Comment
 *
 * @category    Class
 * @description VirtualMachineStatus represents the status returned by the controller to describe how the VirtualMachine is doing
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1VirtualMachineStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1VirtualMachineStatus"
     */
    public function testV1VirtualMachineStatus()
    {
    }

    /**
     * Test attribute "conditions"
     */
    public function testPropertyConditions()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "ready"
     */
    public function testPropertyReady()
    {
    }

    /**
     * Test attribute "snapshot_in_progress"
     */
    public function testPropertySnapshotInProgress()
    {
    }

    /**
     * Test attribute "state_change_requests"
     */
    public function testPropertyStateChangeRequests()
    {
    }

    /**
     * Test attribute "volume_requests"
     */
    public function testPropertyVolumeRequests()
    {
    }

    /**
     * Test attribute "volume_snapshot_statuses"
     */
    public function testPropertyVolumeSnapshotStatuses()
    {
    }
}
