<?php
/**
 * V1VirtualMachineInstanceMigrationStateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1VirtualMachineInstanceMigrationStateTest Class Doc Comment
 *
 * @category    Class
 * @description V1VirtualMachineInstanceMigrationState
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1VirtualMachineInstanceMigrationStateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1VirtualMachineInstanceMigrationState"
     */
    public function testV1VirtualMachineInstanceMigrationState()
    {
    }

    /**
     * Test attribute "abort_requested"
     */
    public function testPropertyAbortRequested()
    {
    }

    /**
     * Test attribute "abort_status"
     */
    public function testPropertyAbortStatus()
    {
    }

    /**
     * Test attribute "completed"
     */
    public function testPropertyCompleted()
    {
    }

    /**
     * Test attribute "end_timestamp"
     */
    public function testPropertyEndTimestamp()
    {
    }

    /**
     * Test attribute "failed"
     */
    public function testPropertyFailed()
    {
    }

    /**
     * Test attribute "migration_uid"
     */
    public function testPropertyMigrationUid()
    {
    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {
    }

    /**
     * Test attribute "source_node"
     */
    public function testPropertySourceNode()
    {
    }

    /**
     * Test attribute "start_timestamp"
     */
    public function testPropertyStartTimestamp()
    {
    }

    /**
     * Test attribute "target_direct_migration_node_ports"
     */
    public function testPropertyTargetDirectMigrationNodePorts()
    {
    }

    /**
     * Test attribute "target_node"
     */
    public function testPropertyTargetNode()
    {
    }

    /**
     * Test attribute "target_node_address"
     */
    public function testPropertyTargetNodeAddress()
    {
    }

    /**
     * Test attribute "target_node_domain_detected"
     */
    public function testPropertyTargetNodeDomainDetected()
    {
    }

    /**
     * Test attribute "target_pod"
     */
    public function testPropertyTargetPod()
    {
    }
}
