<?php
/**
 * V1alpha1VolumeRestore
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * V1alpha1VolumeRestore Class Doc Comment
 *
 * @category Class
 * @description VolumeRestore contains the data neeed to restore a PVC
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class V1alpha1VolumeRestore implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'v1alpha1.VolumeRestore';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'data_volume_name' => 'string',
        'persistent_volume_claim' => 'string',
        'volume_name' => 'string',
        'volume_snapshot_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'data_volume_name' => null,
        'persistent_volume_claim' => null,
        'volume_name' => null,
        'volume_snapshot_name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'data_volume_name' => 'dataVolumeName',
        'persistent_volume_claim' => 'persistentVolumeClaim',
        'volume_name' => 'volumeName',
        'volume_snapshot_name' => 'volumeSnapshotName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'data_volume_name' => 'setDataVolumeName',
        'persistent_volume_claim' => 'setPersistentVolumeClaim',
        'volume_name' => 'setVolumeName',
        'volume_snapshot_name' => 'setVolumeSnapshotName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'data_volume_name' => 'getDataVolumeName',
        'persistent_volume_claim' => 'getPersistentVolumeClaim',
        'volume_name' => 'getVolumeName',
        'volume_snapshot_name' => 'getVolumeSnapshotName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['data_volume_name'] = isset($data['data_volume_name']) ? $data['data_volume_name'] : null;
        $this->container['persistent_volume_claim'] = isset($data['persistent_volume_claim']) ? $data['persistent_volume_claim'] : null;
        $this->container['volume_name'] = isset($data['volume_name']) ? $data['volume_name'] : null;
        $this->container['volume_snapshot_name'] = isset($data['volume_snapshot_name']) ? $data['volume_snapshot_name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['persistent_volume_claim'] === null) {
            $invalidProperties[] = "'persistent_volume_claim' can't be null";
        }
        if ($this->container['volume_name'] === null) {
            $invalidProperties[] = "'volume_name' can't be null";
        }
        if ($this->container['volume_snapshot_name'] === null) {
            $invalidProperties[] = "'volume_snapshot_name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets data_volume_name
     *
     * @return string
     */
    public function getDataVolumeName()
    {
        return $this->container['data_volume_name'];
    }

    /**
     * Sets data_volume_name
     *
     * @param string $data_volume_name data_volume_name
     *
     * @return $this
     */
    public function setDataVolumeName($data_volume_name)
    {
        $this->container['data_volume_name'] = $data_volume_name;

        return $this;
    }

    /**
     * Gets persistent_volume_claim
     *
     * @return string
     */
    public function getPersistentVolumeClaim()
    {
        return $this->container['persistent_volume_claim'];
    }

    /**
     * Sets persistent_volume_claim
     *
     * @param string $persistent_volume_claim persistent_volume_claim
     *
     * @return $this
     */
    public function setPersistentVolumeClaim($persistent_volume_claim)
    {
        $this->container['persistent_volume_claim'] = $persistent_volume_claim;

        return $this;
    }

    /**
     * Gets volume_name
     *
     * @return string
     */
    public function getVolumeName()
    {
        return $this->container['volume_name'];
    }

    /**
     * Sets volume_name
     *
     * @param string $volume_name volume_name
     *
     * @return $this
     */
    public function setVolumeName($volume_name)
    {
        $this->container['volume_name'] = $volume_name;

        return $this;
    }

    /**
     * Gets volume_snapshot_name
     *
     * @return string
     */
    public function getVolumeSnapshotName()
    {
        return $this->container['volume_snapshot_name'];
    }

    /**
     * Sets volume_snapshot_name
     *
     * @param string $volume_snapshot_name volume_snapshot_name
     *
     * @return $this
     */
    public function setVolumeSnapshotName($volume_snapshot_name)
    {
        $this->container['volume_snapshot_name'] = $volume_snapshot_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


