<?php
/**
 * V1CloudInitConfigDriveSource
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * V1CloudInitConfigDriveSource Class Doc Comment
 *
 * @category Class
 * @description Represents a cloud-init config drive user data source. More info: https://cloudinit.readthedocs.io/en/latest/topics/datasources/configdrive.html
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class V1CloudInitConfigDriveSource implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'v1.CloudInitConfigDriveSource';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'network_data' => 'string',
        'network_data_base64' => 'string',
        'network_data_secret_ref' => '\Swagger\Client\Model\K8sIoApiCoreV1LocalObjectReference',
        'secret_ref' => '\Swagger\Client\Model\K8sIoApiCoreV1LocalObjectReference',
        'user_data' => 'string',
        'user_data_base64' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'network_data' => null,
        'network_data_base64' => null,
        'network_data_secret_ref' => null,
        'secret_ref' => null,
        'user_data' => null,
        'user_data_base64' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'network_data' => 'networkData',
        'network_data_base64' => 'networkDataBase64',
        'network_data_secret_ref' => 'networkDataSecretRef',
        'secret_ref' => 'secretRef',
        'user_data' => 'userData',
        'user_data_base64' => 'userDataBase64'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'network_data' => 'setNetworkData',
        'network_data_base64' => 'setNetworkDataBase64',
        'network_data_secret_ref' => 'setNetworkDataSecretRef',
        'secret_ref' => 'setSecretRef',
        'user_data' => 'setUserData',
        'user_data_base64' => 'setUserDataBase64'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'network_data' => 'getNetworkData',
        'network_data_base64' => 'getNetworkDataBase64',
        'network_data_secret_ref' => 'getNetworkDataSecretRef',
        'secret_ref' => 'getSecretRef',
        'user_data' => 'getUserData',
        'user_data_base64' => 'getUserDataBase64'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['network_data'] = isset($data['network_data']) ? $data['network_data'] : null;
        $this->container['network_data_base64'] = isset($data['network_data_base64']) ? $data['network_data_base64'] : null;
        $this->container['network_data_secret_ref'] = isset($data['network_data_secret_ref']) ? $data['network_data_secret_ref'] : null;
        $this->container['secret_ref'] = isset($data['secret_ref']) ? $data['secret_ref'] : null;
        $this->container['user_data'] = isset($data['user_data']) ? $data['user_data'] : null;
        $this->container['user_data_base64'] = isset($data['user_data_base64']) ? $data['user_data_base64'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets network_data
     *
     * @return string
     */
    public function getNetworkData()
    {
        return $this->container['network_data'];
    }

    /**
     * Sets network_data
     *
     * @param string $network_data NetworkData contains config drive inline cloud-init networkdata.
     *
     * @return $this
     */
    public function setNetworkData($network_data)
    {
        $this->container['network_data'] = $network_data;

        return $this;
    }

    /**
     * Gets network_data_base64
     *
     * @return string
     */
    public function getNetworkDataBase64()
    {
        return $this->container['network_data_base64'];
    }

    /**
     * Sets network_data_base64
     *
     * @param string $network_data_base64 NetworkDataBase64 contains config drive cloud-init networkdata as a base64 encoded string.
     *
     * @return $this
     */
    public function setNetworkDataBase64($network_data_base64)
    {
        $this->container['network_data_base64'] = $network_data_base64;

        return $this;
    }

    /**
     * Gets network_data_secret_ref
     *
     * @return \Swagger\Client\Model\K8sIoApiCoreV1LocalObjectReference
     */
    public function getNetworkDataSecretRef()
    {
        return $this->container['network_data_secret_ref'];
    }

    /**
     * Sets network_data_secret_ref
     *
     * @param \Swagger\Client\Model\K8sIoApiCoreV1LocalObjectReference $network_data_secret_ref NetworkDataSecretRef references a k8s secret that contains config drive networkdata.
     *
     * @return $this
     */
    public function setNetworkDataSecretRef($network_data_secret_ref)
    {
        $this->container['network_data_secret_ref'] = $network_data_secret_ref;

        return $this;
    }

    /**
     * Gets secret_ref
     *
     * @return \Swagger\Client\Model\K8sIoApiCoreV1LocalObjectReference
     */
    public function getSecretRef()
    {
        return $this->container['secret_ref'];
    }

    /**
     * Sets secret_ref
     *
     * @param \Swagger\Client\Model\K8sIoApiCoreV1LocalObjectReference $secret_ref UserDataSecretRef references a k8s secret that contains config drive userdata.
     *
     * @return $this
     */
    public function setSecretRef($secret_ref)
    {
        $this->container['secret_ref'] = $secret_ref;

        return $this;
    }

    /**
     * Gets user_data
     *
     * @return string
     */
    public function getUserData()
    {
        return $this->container['user_data'];
    }

    /**
     * Sets user_data
     *
     * @param string $user_data UserData contains config drive inline cloud-init userdata.
     *
     * @return $this
     */
    public function setUserData($user_data)
    {
        $this->container['user_data'] = $user_data;

        return $this;
    }

    /**
     * Gets user_data_base64
     *
     * @return string
     */
    public function getUserDataBase64()
    {
        return $this->container['user_data_base64'];
    }

    /**
     * Sets user_data_base64
     *
     * @param string $user_data_base64 UserDataBase64 contains config drive cloud-init userdata as a base64 encoded string.
     *
     * @return $this
     */
    public function setUserDataBase64($user_data_base64)
    {
        $this->container['user_data_base64'] = $user_data_base64;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


