<?php
/**
 * V1KubeVirtSelfSignConfiguration
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * V1KubeVirtSelfSignConfiguration Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class V1KubeVirtSelfSignConfiguration implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'v1.KubeVirtSelfSignConfiguration';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ca_overlap_interval' => '\Swagger\Client\Model\K8sIoApimachineryPkgApisMetaV1Duration',
        'ca_rotate_interval' => '\Swagger\Client\Model\K8sIoApimachineryPkgApisMetaV1Duration',
        'cert_rotate_interval' => '\Swagger\Client\Model\K8sIoApimachineryPkgApisMetaV1Duration'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ca_overlap_interval' => null,
        'ca_rotate_interval' => null,
        'cert_rotate_interval' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ca_overlap_interval' => 'caOverlapInterval',
        'ca_rotate_interval' => 'caRotateInterval',
        'cert_rotate_interval' => 'certRotateInterval'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ca_overlap_interval' => 'setCaOverlapInterval',
        'ca_rotate_interval' => 'setCaRotateInterval',
        'cert_rotate_interval' => 'setCertRotateInterval'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ca_overlap_interval' => 'getCaOverlapInterval',
        'ca_rotate_interval' => 'getCaRotateInterval',
        'cert_rotate_interval' => 'getCertRotateInterval'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ca_overlap_interval'] = isset($data['ca_overlap_interval']) ? $data['ca_overlap_interval'] : null;
        $this->container['ca_rotate_interval'] = isset($data['ca_rotate_interval']) ? $data['ca_rotate_interval'] : null;
        $this->container['cert_rotate_interval'] = isset($data['cert_rotate_interval']) ? $data['cert_rotate_interval'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ca_overlap_interval
     *
     * @return \Swagger\Client\Model\K8sIoApimachineryPkgApisMetaV1Duration
     */
    public function getCaOverlapInterval()
    {
        return $this->container['ca_overlap_interval'];
    }

    /**
     * Sets ca_overlap_interval
     *
     * @param \Swagger\Client\Model\K8sIoApimachineryPkgApisMetaV1Duration $ca_overlap_interval ca_overlap_interval
     *
     * @return $this
     */
    public function setCaOverlapInterval($ca_overlap_interval)
    {
        $this->container['ca_overlap_interval'] = $ca_overlap_interval;

        return $this;
    }

    /**
     * Gets ca_rotate_interval
     *
     * @return \Swagger\Client\Model\K8sIoApimachineryPkgApisMetaV1Duration
     */
    public function getCaRotateInterval()
    {
        return $this->container['ca_rotate_interval'];
    }

    /**
     * Sets ca_rotate_interval
     *
     * @param \Swagger\Client\Model\K8sIoApimachineryPkgApisMetaV1Duration $ca_rotate_interval ca_rotate_interval
     *
     * @return $this
     */
    public function setCaRotateInterval($ca_rotate_interval)
    {
        $this->container['ca_rotate_interval'] = $ca_rotate_interval;

        return $this;
    }

    /**
     * Gets cert_rotate_interval
     *
     * @return \Swagger\Client\Model\K8sIoApimachineryPkgApisMetaV1Duration
     */
    public function getCertRotateInterval()
    {
        return $this->container['cert_rotate_interval'];
    }

    /**
     * Sets cert_rotate_interval
     *
     * @param \Swagger\Client\Model\K8sIoApimachineryPkgApisMetaV1Duration $cert_rotate_interval cert_rotate_interval
     *
     * @return $this
     */
    public function setCertRotateInterval($cert_rotate_interval)
    {
        $this->container['cert_rotate_interval'] = $cert_rotate_interval;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


