<?php
/**
 * K8sIoApiCoreV1PersistentVolumeClaimSpecTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * K8sIoApiCoreV1PersistentVolumeClaimSpecTest Class Doc Comment
 *
 * @category    Class
 * @description PersistentVolumeClaimSpec describes the common attributes of storage devices and allows a Source for provider-specific attributes
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class K8sIoApiCoreV1PersistentVolumeClaimSpecTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "K8sIoApiCoreV1PersistentVolumeClaimSpec"
     */
    public function testK8sIoApiCoreV1PersistentVolumeClaimSpec()
    {
    }

    /**
     * Test attribute "access_modes"
     */
    public function testPropertyAccessModes()
    {
    }

    /**
     * Test attribute "data_source"
     */
    public function testPropertyDataSource()
    {
    }

    /**
     * Test attribute "resources"
     */
    public function testPropertyResources()
    {
    }

    /**
     * Test attribute "selector"
     */
    public function testPropertySelector()
    {
    }

    /**
     * Test attribute "storage_class_name"
     */
    public function testPropertyStorageClassName()
    {
    }

    /**
     * Test attribute "volume_mode"
     */
    public function testPropertyVolumeMode()
    {
    }

    /**
     * Test attribute "volume_name"
     */
    public function testPropertyVolumeName()
    {
    }
}
