<?php
/**
 * V1FeatureHypervTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1FeatureHypervTest Class Doc Comment
 *
 * @category    Class
 * @description Hyperv specific features.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1FeatureHypervTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1FeatureHyperv"
     */
    public function testV1FeatureHyperv()
    {
    }

    /**
     * Test attribute "evmcs"
     */
    public function testPropertyEvmcs()
    {
    }

    /**
     * Test attribute "frequencies"
     */
    public function testPropertyFrequencies()
    {
    }

    /**
     * Test attribute "ipi"
     */
    public function testPropertyIpi()
    {
    }

    /**
     * Test attribute "reenlightenment"
     */
    public function testPropertyReenlightenment()
    {
    }

    /**
     * Test attribute "relaxed"
     */
    public function testPropertyRelaxed()
    {
    }

    /**
     * Test attribute "reset"
     */
    public function testPropertyReset()
    {
    }

    /**
     * Test attribute "runtime"
     */
    public function testPropertyRuntime()
    {
    }

    /**
     * Test attribute "spinlocks"
     */
    public function testPropertySpinlocks()
    {
    }

    /**
     * Test attribute "synic"
     */
    public function testPropertySynic()
    {
    }

    /**
     * Test attribute "synictimer"
     */
    public function testPropertySynictimer()
    {
    }

    /**
     * Test attribute "tlbflush"
     */
    public function testPropertyTlbflush()
    {
    }

    /**
     * Test attribute "vapic"
     */
    public function testPropertyVapic()
    {
    }

    /**
     * Test attribute "vendorid"
     */
    public function testPropertyVendorid()
    {
    }

    /**
     * Test attribute "vpindex"
     */
    public function testPropertyVpindex()
    {
    }
}
