<?php
/**
 * V1KubeVirtSpecTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1KubeVirtSpecTest Class Doc Comment
 *
 * @category    Class
 * @description V1KubeVirtSpec
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1KubeVirtSpecTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1KubeVirtSpec"
     */
    public function testV1KubeVirtSpec()
    {
    }

    /**
     * Test attribute "certificate_rotate_strategy"
     */
    public function testPropertyCertificateRotateStrategy()
    {
    }

    /**
     * Test attribute "configuration"
     */
    public function testPropertyConfiguration()
    {
    }

    /**
     * Test attribute "customize_components"
     */
    public function testPropertyCustomizeComponents()
    {
    }

    /**
     * Test attribute "image_pull_policy"
     */
    public function testPropertyImagePullPolicy()
    {
    }

    /**
     * Test attribute "image_registry"
     */
    public function testPropertyImageRegistry()
    {
    }

    /**
     * Test attribute "image_tag"
     */
    public function testPropertyImageTag()
    {
    }

    /**
     * Test attribute "infra"
     */
    public function testPropertyInfra()
    {
    }

    /**
     * Test attribute "monitor_account"
     */
    public function testPropertyMonitorAccount()
    {
    }

    /**
     * Test attribute "monitor_namespace"
     */
    public function testPropertyMonitorNamespace()
    {
    }

    /**
     * Test attribute "product_name"
     */
    public function testPropertyProductName()
    {
    }

    /**
     * Test attribute "product_version"
     */
    public function testPropertyProductVersion()
    {
    }

    /**
     * Test attribute "uninstall_strategy"
     */
    public function testPropertyUninstallStrategy()
    {
    }

    /**
     * Test attribute "workload_update_strategy"
     */
    public function testPropertyWorkloadUpdateStrategy()
    {
    }

    /**
     * Test attribute "workloads"
     */
    public function testPropertyWorkloads()
    {
    }
}
