<?php
/**
 * V1KubeVirtConfigurationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1KubeVirtConfigurationTest Class Doc Comment
 *
 * @category    Class
 * @description KubeVirtConfiguration holds all kubevirt configurations
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1KubeVirtConfigurationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1KubeVirtConfiguration"
     */
    public function testV1KubeVirtConfiguration()
    {
    }

    /**
     * Test attribute "cpu_model"
     */
    public function testPropertyCpuModel()
    {
    }

    /**
     * Test attribute "cpu_request"
     */
    public function testPropertyCpuRequest()
    {
    }

    /**
     * Test attribute "developer_configuration"
     */
    public function testPropertyDeveloperConfiguration()
    {
    }

    /**
     * Test attribute "emulated_machines"
     */
    public function testPropertyEmulatedMachines()
    {
    }

    /**
     * Test attribute "image_pull_policy"
     */
    public function testPropertyImagePullPolicy()
    {
    }

    /**
     * Test attribute "machine_type"
     */
    public function testPropertyMachineType()
    {
    }

    /**
     * Test attribute "mem_balloon_stats_period"
     */
    public function testPropertyMemBalloonStatsPeriod()
    {
    }

    /**
     * Test attribute "migrations"
     */
    public function testPropertyMigrations()
    {
    }

    /**
     * Test attribute "min_cpu_model"
     */
    public function testPropertyMinCpuModel()
    {
    }

    /**
     * Test attribute "network"
     */
    public function testPropertyNetwork()
    {
    }

    /**
     * Test attribute "obsolete_cpu_models"
     */
    public function testPropertyObsoleteCpuModels()
    {
    }

    /**
     * Test attribute "ovmf_path"
     */
    public function testPropertyOvmfPath()
    {
    }

    /**
     * Test attribute "permitted_host_devices"
     */
    public function testPropertyPermittedHostDevices()
    {
    }

    /**
     * Test attribute "selinux_launcher_type"
     */
    public function testPropertySelinuxLauncherType()
    {
    }

    /**
     * Test attribute "smbios"
     */
    public function testPropertySmbios()
    {
    }

    /**
     * Test attribute "supported_guest_agent_versions"
     */
    public function testPropertySupportedGuestAgentVersions()
    {
    }
}
