<?php
/**
 * V1VirtualMachineInstanceReplicaSetStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1VirtualMachineInstanceReplicaSetStatusTest Class Doc Comment
 *
 * @category    Class
 * @description V1VirtualMachineInstanceReplicaSetStatus
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1VirtualMachineInstanceReplicaSetStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1VirtualMachineInstanceReplicaSetStatus"
     */
    public function testV1VirtualMachineInstanceReplicaSetStatus()
    {
    }

    /**
     * Test attribute "conditions"
     */
    public function testPropertyConditions()
    {
    }

    /**
     * Test attribute "label_selector"
     */
    public function testPropertyLabelSelector()
    {
    }

    /**
     * Test attribute "ready_replicas"
     */
    public function testPropertyReadyReplicas()
    {
    }

    /**
     * Test attribute "replicas"
     */
    public function testPropertyReplicas()
    {
    }
}
