<?php
/**
 * V1VolumeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KubeVirt API
 *
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1VolumeTest Class Doc Comment
 *
 * @category    Class
 * @description Volume represents a named volume in a vmi.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1VolumeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1Volume"
     */
    public function testV1Volume()
    {
    }

    /**
     * Test attribute "cloud_init_config_drive"
     */
    public function testPropertyCloudInitConfigDrive()
    {
    }

    /**
     * Test attribute "cloud_init_no_cloud"
     */
    public function testPropertyCloudInitNoCloud()
    {
    }

    /**
     * Test attribute "config_map"
     */
    public function testPropertyConfigMap()
    {
    }

    /**
     * Test attribute "container_disk"
     */
    public function testPropertyContainerDisk()
    {
    }

    /**
     * Test attribute "data_volume"
     */
    public function testPropertyDataVolume()
    {
    }

    /**
     * Test attribute "downward_api"
     */
    public function testPropertyDownwardApi()
    {
    }

    /**
     * Test attribute "empty_disk"
     */
    public function testPropertyEmptyDisk()
    {
    }

    /**
     * Test attribute "ephemeral"
     */
    public function testPropertyEphemeral()
    {
    }

    /**
     * Test attribute "host_disk"
     */
    public function testPropertyHostDisk()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "persistent_volume_claim"
     */
    public function testPropertyPersistentVolumeClaim()
    {
    }

    /**
     * Test attribute "secret"
     */
    public function testPropertySecret()
    {
    }

    /**
     * Test attribute "service_account"
     */
    public function testPropertyServiceAccount()
    {
    }

    /**
     * Test attribute "sysprep"
     */
    public function testPropertySysprep()
    {
    }
}
